[package]
name = "wadl"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "A WADL parser for Rust"
repository = "https://github.com/jelmer/wadl-rs"
authors = ["Jelmer Vernooĳ <jelmer@jelmer.uk>"]
default-run = "wadlc"

[dependencies]
clap = { version = "4.4.6", features = ["derive", "env"], optional = true }
env_logger = { version = "0.10.0", optional = true }
lazy_static = "1.4.0"
log = "0.4.20"
mime = "0.3.17"
proc-macro2 = { version = "1", optional = true }
quote = { version = "1", optional = true }
syn = { version = "2", optional = true }
url = "2.4"
xmltree = "0.10.3"

[features]
default = ["cli"]
codegen = ["dep:proc-macro2", "dep:quote", "dep:syn"]
cli = ["dep:clap", "dep:env_logger", "codegen"]

[[bin]]
name = "wadlc"
path = "src/bin/wadlc.rs"
required-features = ["cli"]
