[package]
name = "wadl"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A WADL parser for Rust"
repository = "https://github.com/jelmer/wadl-rs"
authors = ["Jelmer Vernooĳ <jelmer@jelmer.uk>"]

[dependencies]
clap = { version = "4.4.6", features = ["derive", "env"], optional = true }
lazy_static = "1.4.0"
xml = "0.8.10"
xmltree = "0.10.3"

[features]
default = ["cli"]
cli = ["clap"]

[[bin]]
name = "wadlc"
path = "src/bin/wadlc.rs"
required-features = ["cli"]
